---
#------------------------------------------------------
#                        Header
#------------------------------------------------------
# Action name and Its triggers
name: Docker push
on: workflow_dispatch

#------------------------------------------------------
#                      Variables
#------------------------------------------------------
# env:
#   ECR_REPOSITORY: "samurai"
#   AWS_REGION: "us-east-2"

#------------------------------------------------------
#                 Beginning of the jobs
#------------------------------------------------------
jobs:

  #------------------------------------------------------
  # job 01 - Build e Push do container para o Docker Hub
  #------------------------------------------------------
  push:
    name: Publica a Imagem
    runs-on: ubuntu-18.04
    steps:
      #---------------------step 04-01-----------------------
      - name: Checkout
        uses: actions/checkout@v2
      #---------------------step 04-02-----------------------
      - name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      #---------------------step 04-07-----------------------
      - name: Create Short SHA Commit
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
      #---------------------step 04-08-----------------------
      - name: Create Image Tag
        run: echo "IMAGE_TAG=$SHORT_SHA-$(date --utc +%Y%m%d%H%M%S)" >> $GITHUB_ENV
      #---------------------step 04-06-----------------------
      - name: Build, tag, and push image to Docker Hub
        run: |
          docker build -t mmmarceleza/app4:$IMAGE_TAG .
          docker push mmmarceleza/app4:$IMAGE_TAG
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_ORGANIZATION }}:$IMAGE_TAG
