---
#------------------------------------------------------
#                        Header
#------------------------------------------------------
# Action name and Its triggers
name: Health Check Success
on: workflow_dispatch

#------------------------------------------------------
#                      Variables
#------------------------------------------------------

#------------------------------------------------------
#                 Beginning of the jobs
#------------------------------------------------------
jobs:
  #------------------------------------------------------
  #              Job 01 - Notify Sucess
  #------------------------------------------------------
  notify:
    name: Notify Sucess
    runs-on: ubuntu-18.04
    steps:
      #---------------------step 01-01-------------------
      - name: Echo Success
        run: echo "Health check successes"

  #------------------------------------------------------
  #             Job 02 - Rename Docker Image
  #------------------------------------------------------
  tag:
    name: Tag Image Production
    runs-on: ubuntu-18.04
    steps:
      #---------------------step 02-01-----------------------
      # - name: Checkout
      #   uses: actions/checkout@v2    
      #---------------------step 02-02-----------------------
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1          
      #---------------------step 02-03-------------------
      - name: Download image
        run: | 
          # git config --global credential.https://github.com.helper ''
          # git config --global --add credential.https://github.com.helper '!'$(which gh)' auth git-credential'
          # gh repo clone ci-test
          # cd ci-test
          gh run download -n myimage
          docker load --input myimage.tar
          docker images
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
