---
#------------------------------------------------------
#                        Header
#------------------------------------------------------
# Action name and Its triggers
name: Health Check Success
on: workflow_dispatch

#------------------------------------------------------
#                      Variables
#------------------------------------------------------

#------------------------------------------------------
#                 Beginning of the jobs
#------------------------------------------------------
jobs:
  #------------------------------------------------------
  #              job 01 -
  #------------------------------------------------------
  lint:
    name: Dockerfile Linter
    runs-on: ubuntu-18.04
    steps:
      #---------------------step 01-01-------------------
      - name: Echo Success
        run: echo "Health check successes"
