---
#------------------------------------------------------
#                        Header
#------------------------------------------------------
# Action name and Its triggers
name: Health Check Failed
on: workflow_dispatch

#------------------------------------------------------
#                      Variables
#------------------------------------------------------

#------------------------------------------------------
#                 Beginning of the jobs
#------------------------------------------------------
jobs:
  #------------------------------------------------------
  #              job 01 -
  #------------------------------------------------------
  lint:
    name: Echo Failed
    runs-on: [self-hosted, linux, ARM64]
    steps:
      #---------------------step 01-01-------------------
      - name: Echo Failed
        run: echo "Health check failed"
